In [1]:
import os
import shutil
import math

def get_utm_coordinates(filename):
    parts = filename.split('@')
    utm_easting = float(parts[1])
    utm_northing = float(parts[2])
    return utm_easting, utm_northing

In [3]:
def calculate_euclidean_distance(coord1, coord2):
    return math.sqrt((coord1[0] - coord2[0]) ** 2 + (coord1[1] - coord2[1]) ** 2)


In [17]:
import numpy as np

def copy_images_within_distance(db_folder, q_folder, distance_threshold):
    
    db_images = [f for f in os.listdir(db_folder) ]
    q_images = [f for f in os.listdir(q_folder) ]
    
    gt = ([[] for i in range(len(q_images))])
    
    for idxq,q_image in enumerate(q_images):
        q_utm = get_utm_coordinates(q_image)
        
        for idxdb,db_image in enumerate(db_images):
            db_utm = get_utm_coordinates(db_image)
            distance = calculate_euclidean_distance(q_utm, db_utm)
            
            if distance <= distance_threshold:
                gt[idxq].append(idxdb)
                

    return np.array(gt, dtype=object)

In [53]:





# Define folder paths
db_folder = '/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/robotcar_dataset/val/database/sequence'
q_folder = '/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/robotcar_dataset/val/queries/sequence'

# Define distance threshold in meters
distance_threshold = 25

# Copy images within the distance threshold
gt = copy_images_within_distance(db_folder, q_folder, distance_threshold)


In [ ]:
gt

In [50]:
gt_images_file = '/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/RobotCar/robotcar_val_qImages.npy'

np.save(gt_images_file, gt)


In [ ]:
gt = np.load(gt_images_file, allow_pickle=True)
gt

In [26]:
import matplotlib.pyplot as plt

def show_image(image, title):
    plt.imshow(image)
    plt.title(title)
    plt.axis('off')
    plt.show()

Matplotlib is building the font cache; this may take a moment.


In [14]:
q_images = [f for f in os.listdir(q_folder) if f.endswith('.jpg')]
print(f"Total number of images in the ground truth folder: {len(q_images)}")

Total number of images in the ground truth folder: 1000


In [15]:
db_images = [f for f in os.listdir(db_folder)]
print(f"Total number of images in the ground truth folder: {len(db_images)}")

Total number of images in the ground truth folder: 27191


In [17]:
gt_images = [f for f in os.listdir(gt_folder)]
print(f"Total number of images in the ground truth folder: {len(gt_images)}")

Total number of images in the ground truth folder: 7665


In [ ]:
import os

def compare_folders(folder1, folder2):
    """
    Compares the image filenames in two folders and returns True if they contain the same files.
    """
    files_in_folder1 = set(f for f in os.listdir(folder1) if f.endswith('.jpg'))
    files_in_folder2 = set(f for f in os.listdir(folder2) if f.endswith('.jpg'))
    
    return files_in_folder1 == files_in_folder2

# Define the folder paths
folder1 = 'path/to/first/folder'
folder2 = 'path/to/second/folder'

# Compare the folders
folders_are_equal = compare_folders(folder1, folder2)
print(f"The folders contain the same files: {folders_are_equal}")


## Save files

In [14]:
import numpy as np

# Load the .npy files
gt_images = np.load('/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/CrossSeason/CrossSeason_gt.npy', allow_pickle=True)

In [15]:
gt_images

array([array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([19, 20, 21, 22, 23, 24, 25]),
       array([19, 20, 21, 22

In [60]:
import os
import numpy as np

# Define the paths
base_dir = '/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/robotcar_dataset/'
database_dir = os.path.join(base_dir, 'test/database/sequence')
queries_dir = os.path.join(base_dir, 'test/queries/sequence')
db_images_file = 'robotcar_test_dbImages.npy'
q_images_file = 'robotcar_test_qImages.npy'

print(database_dir)

# Function to get relative image paths
def get_image_paths(dir_path, base_dir):
    image_paths = []
    for root, dirs, files in os.walk(dir_path):
        for file in files:
            if file.endswith(('.png', '.jpg', '.jpeg')):
                full_path = os.path.join(root, file)
                relative_path = os.path.relpath(full_path, base_dir)
                image_paths.append(relative_path)
    return image_paths

# Get all image file names in the database and queries folders
db_images = get_image_paths(database_dir, base_dir)
q_images = get_image_paths(queries_dir, base_dir)

# Save the image file names to numpy arrays
np.save(db_images_file, np.array(db_images))
np.save(q_images_file, np.array(q_images))

# Print confirmation
print(f'Saved {len(db_images)} database image names to {db_images_file}')
print(f'Saved {len(q_images)} query image names to {q_images_file}')


/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/robotcar_dataset/test/database/sequence
Saved 3632 database image names to robotcar_test_dbImages.npy
Saved 3921 query image names to robotcar_test_qImages.npy
